// Anseo TypeScript SDK — orval config (Story 12.3).
//
// Generates a Promise-based client into packages/typescript/src/ from
// the canonical OpenAPI artifact. Pinned to orval 7.1.0 in the
// Makefile; a generator bump goes through a PR with the regenerated
// diff so the drift gate stays green.

module.exports = {
  anseo: {
    input: {
      target: "../../crates/wire-schema/openapi.json",
    },
    output: {
      mode: "split",
      target: "../../packages/typescript/src/client.ts",
      schemas: "../../packages/typescript/src/schemas",
      client: "fetch",
      override: {
        mutator: {
          path: "../../packages/typescript/src/runtime.ts",
          name: "fetchClient",
        },
        header: () =>
          [
            "/*",
            " * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.",
            " * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.",
            " */",
            "",
          ].join("\n"),
      },
      prettier: true,
    },
  },
};
