/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { AnalyticsSiteOverviewPeriod } from './analyticsSiteOverviewPeriod';

export type AnalyticsSiteOverviewParams = {
/**
 * Trailing window. Defaults to 7d; any unsupported value clamps to 7d.
 */
period?: AnalyticsSiteOverviewPeriod;
};
