/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { AnalyticsFunnelsPeriod } from './analyticsFunnelsPeriod';

export type AnalyticsFunnelsParams = {
/**
 * Trailing window for the contribute + verify funnels. Defaults to 7d; any unsupported value clamps to 7d. Badge embeds are always last 30 d.
 */
period?: AnalyticsFunnelsPeriod;
};
