/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type AnalyticsSiteOverviewPeriod = typeof AnalyticsSiteOverviewPeriod[keyof typeof AnalyticsSiteOverviewPeriod];


export const AnalyticsSiteOverviewPeriod = {
  '7d': '7d',
  '30d': '30d',
} as const;
