/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { AuditFindingCategory } from './auditFindingCategory';
import type { AuditFindingSeverity } from './auditFindingSeverity';
import type { AuditFindingStatus } from './auditFindingStatus';

export interface AuditFinding {
  rule_id: string;
  category: AuditFindingCategory;
  severity: AuditFindingSeverity;
  status: AuditFindingStatus;
  /**
     * @minimum 0
     * @maximum 100
     */
  score: number;
  message: string;
  recommendation_kind: string;
  evidence: string[];
}
