/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type AuditFindingSeverity = typeof AuditFindingSeverity[keyof typeof AuditFindingSeverity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditFindingSeverity = {
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const;
