/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export interface AuditRunItem {
  id: string;
  target: string;
  /**
     * @minimum 0
     * @maximum 100
     */
  overall_score: number;
  /** @minimum 0 */
  pages_crawled: number;
  /** @nullable */
  gate_passed?: boolean | null;
  created_at: string;
}
