/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { AuditReportGate } from './auditReportGate';
import type { PageAudit } from './pageAudit';

export interface AuditReport {
  /** @nullable */
  gate?: AuditReportGate;
  /**
   * @minimum 0
   * @maximum 100
   */
  overall_score: number;
  pages: PageAudit[];
  target: string;
}
