/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type AuditFindingCategory = typeof AuditFindingCategory[keyof typeof AuditFindingCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditFindingCategory = {
  identity: 'identity',
  extractability: 'extractability',
  corroboration: 'corroboration',
} as const;
