/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type AuditFindingStatus = typeof AuditFindingStatus[keyof typeof AuditFindingStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditFindingStatus = {
  pass: 'pass',
  warn: 'warn',
  fail: 'fail',
} as const;
