/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { GateSummary } from './gateSummary';
import type { PageAudit } from './pageAudit';

export interface AuditReport {
  target: string;
  /**
     * @minimum 0
     * @maximum 100
     */
  overall_score: number;
  pages: PageAudit[];
  gate?: GateSummary | null;
}
