/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { AuditFindingCategory } from './auditFindingCategory';
import type { AuditFindingSeverity } from './auditFindingSeverity';
import type { AuditFindingStatus } from './auditFindingStatus';

export interface AuditFinding {
  category: AuditFindingCategory;
  evidence: string[];
  message: string;
  recommendation_kind: string;
  rule_id: string;
  /**
   * @minimum 0
   * @maximum 100
   */
  score: number;
  severity: AuditFindingSeverity;
  status: AuditFindingStatus;
}
