/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { BrandCompetitor } from './brandCompetitor';

export interface BrandUpdateResult {
  project_id: string;
  name: string;
  variants: string[];
  competitors: BrandCompetitor[];
  /** @nullable */
  site_url?: string | null;
  restart_required: boolean;
}
