/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { BrandCompetitor } from './brandCompetitor';

export interface BrandUpdate {
  competitors?: BrandCompetitor[];
  name: string;
  /** @nullable */
  site_url?: string | null;
  variants?: string[];
}
