/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { CitationSummaryResponseDomainsItem } from './citationSummaryResponseDomainsItem';

export interface CitationSummaryResponse {
  domains?: CitationSummaryResponseDomainsItem[];
}
