/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { ClaimVerdictStatus } from './claimVerdictStatus';

export interface ClaimVerdict {
  claim_kind: string;
  claim_text: string;
  entity: string;
  /** @nullable */
  matched_fact_key?: string | null;
  observed_at: string;
  prompt_run_id: string;
  rationale: string;
  status: ClaimVerdictStatus;
}
