/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type ClaimVerdictStatus = typeof ClaimVerdictStatus[keyof typeof ClaimVerdictStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClaimVerdictStatus = {
  accurate: 'accurate',
  inaccurate: 'inaccurate',
  unverifiable: 'unverifiable',
} as const;
