/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type ClickHouseInstallEventStep = typeof ClickHouseInstallEventStep[keyof typeof ClickHouseInstallEventStep];


export const ClickHouseInstallEventStep = {
  docker_detected: 'docker_detected',
  image_pulling: 'image_pulling',
  container_starting: 'container_starting',
  provisioning_user: 'provisioning_user',
  applying_migrations: 'applying_migrations',
  running_parity_test: 'running_parity_test',
  complete: 'complete',
} as const;
