/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { ClickHouseInstallEventStep } from './clickHouseInstallEventStep';

/**
 * Story 15.1 — one frame of the SSE install stream. Step ordering: docker_detected → image_pulling → container_starting → provisioning_user → applying_migrations → running_parity_test → complete.
 */
export interface ClickHouseInstallEvent {
  at: string;
  log_line: string;
  /**
     * @minimum 0
     * @maximum 1
     */
  progress: number;
  step: ClickHouseInstallEventStep;
}
