/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type ComparisonsResponseWindow = typeof ComparisonsResponseWindow[keyof typeof ComparisonsResponseWindow];


export const ComparisonsResponseWindow = {
  '7d': '7d',
  '30d': '30d',
  all: 'all',
} as const;
