/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { ComparisonRow } from './comparisonRow';
import type { ComparisonsResponseWindow } from './comparisonsResponseWindow';

/**
 * Story 0.8 `GET /v1/comparisons` matrix payload — mirrors the MCP CompareBrandsOutput shape (architecture-phase3-mcp-server.md §3.3). Determinism contract: rows ordered (prompt_name ASC, provider ASC); cells ordered [brand, ...competitors_in_caller_order]; absent subjects carry ranking:null (NOT omitted).
 */
export interface ComparisonsResponse {
  brand: string;
  competitors: string[];
  rows: ComparisonRow[];
  trace_id: string;
  window: ComparisonsResponseWindow;
}
