/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { ComparisonCell } from './comparisonCell';

export interface ComparisonRow {
  cells: ComparisonCell[];
  /** ULID. */
  prompt_id: string;
  prompt_name: string;
  provider: string;
}
