/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type ComparisonsWindow = typeof ComparisonsWindow[keyof typeof ComparisonsWindow];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ComparisonsWindow = {
  '1d': '1d',
  '7d': '7d',
  '30d': '30d',
} as const;
