/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { ComparisonsWindow } from './comparisonsWindow';

export type ComparisonsParams = {
brands: string;
prompts?: string;
providers?: string;
window?: ComparisonsWindow;
};
