/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export interface ComparisonCell {
  /** @minimum 0 */
  mention_count: number;
  /**
     * @minimum 1
     * @nullable
     */
  ranking?: number | null;
  subject: string;
}
