/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { ContributionStatusStatus } from './contributionStatusStatus';

/**
 * Outcome of the benchmark consent + envelope gate. `sealed`: opted in with a KEK, redacted + sealed. `skipped_not_opted_in`: no active opt-in. `kek_missing`: opted in but no per-project KEK available, so the contribution could NOT be sealed (the run is still recorded; benchmark data is flagged, never silently dropped). `redaction_rejected`: redaction refused the run (e.g. stale consent terms).
 */
export interface ContributionStatus {
  /**
   * Present only when status is redaction_rejected.
   * @nullable
   */
  reason?: string | null;
  status: ContributionStatusStatus;
}
