/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type ContributionStatusStatus = typeof ContributionStatusStatus[keyof typeof ContributionStatusStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContributionStatusStatus = {
  sealed: 'sealed',
  skipped_not_opted_in: 'skipped_not_opted_in',
  kek_missing: 'kek_missing',
  redaction_rejected: 'redaction_rejected',
} as const;
