/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export interface CrawlerPathMetric {
  error_hits: number;
  hits: number;
  path: string;
}
