/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { CrawlReferRatio } from './crawlReferRatio';
import type { CrawlReferState } from './crawlReferState';

/**
 * Roadmap Epic 33 crawl-to-refer ratio. When referral attribution is unavailable, state is crawls_only and ratio is null.
 */
export interface CrawlReferReport {
  window_start: string;
  window_end: string;
  state: CrawlReferState;
  bots: CrawlReferRatio[];
}
