/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { CrawlReferState } from './crawlReferState';

export interface CrawlReferRatio {
  attributed_referrals: number;
  bot_id: string;
  /** @nullable */
  ratio?: number | null;
  state: CrawlReferState;
  verified_crawl_hits: number;
}
