/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export interface CrawlerBotMetric {
  bot_id: string;
  error_hits: number;
  hits: number;
  verified_hits: number;
}
