/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export interface CrawlerIngestResult {
  /** @minimum 0 */
  ingested: number;
  /** @minimum 0 */
  parsed: number;
  /** @minimum 0 */
  skipped: number;
}
