/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type CrawlerIngestRequestPrivacyMode = typeof CrawlerIngestRequestPrivacyMode[keyof typeof CrawlerIngestRequestPrivacyMode];


export const CrawlerIngestRequestPrivacyMode = {
  hashed: 'hashed',
  truncated: 'truncated',
  raw: 'raw',
} as const;
