/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { CrawlerBotMetric } from './crawlerBotMetric';
import type { CrawlerPathMetric } from './crawlerPathMetric';
import type { CrawlerTrendBucket } from './crawlerTrendBucket';

/**
 * Roadmap Epic 31 crawler observability metrics. Headline payloads exclude unverified crawler hits unless `include_unverified=true` is requested.
 */
export interface CrawlerMetricsResponse {
  bots: CrawlerBotMetric[];
  error_paths: CrawlerPathMetric[];
  include_unverified: boolean;
  top_paths: CrawlerPathMetric[];
  trend: CrawlerTrendBucket[];
  window_end: string;
  window_start: string;
}
