/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type CrawlReferState = typeof CrawlReferState[keyof typeof CrawlReferState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrawlReferState = {
  complete: 'complete',
  crawls_only: 'crawls_only',
} as const;
