/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type CrawlerMetricsParams = {
days?: number;
include_unverified?: boolean;
};
