/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type CrawlerIngestRequestFormat = typeof CrawlerIngestRequestFormat[keyof typeof CrawlerIngestRequestFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrawlerIngestRequestFormat = {
  common: 'common',
  combined: 'combined',
} as const;
