/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { CrawlerIngestRequestFormat } from './crawlerIngestRequestFormat';
import type { CrawlerIngestRequestPrivacyMode } from './crawlerIngestRequestPrivacyMode';

export interface CrawlerIngestRequest {
  format?: CrawlerIngestRequestFormat;
  /** Raw access-log lines (nginx/Apache), one hit per line. */
  lines: string[];
  privacy_mode?: CrawlerIngestRequestPrivacyMode;
}
