/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export interface CreatePromptRunResponse {
  dispatched_at: string;
  project_id: string;
  prompt_name: string;
  provider: string;
  run_id: string;
  status: string;
}
