/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type CreatePromptRunRequestProvider = typeof CreatePromptRunRequestProvider[keyof typeof CreatePromptRunRequestProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePromptRunRequestProvider = {
  openai: 'openai',
  anthropic: 'anthropic',
  gemini: 'gemini',
  perplexity: 'perplexity',
  grok: 'grok',
  mistral: 'mistral',
  openrouter: 'openrouter',
  mock: 'mock',
} as const;
