/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export interface CreateProjectRequest {
  name: string;
  variants?: string[];
  /** @nullable */
  site_url?: string | null;
}
