/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { CreatePromptRunRequestProvider } from './createPromptRunRequestProvider';

export interface CreatePromptRunRequest {
  /** Slug-safe prompt identifier declared in anseo.yaml. */
  prompt_name: string;
  provider: CreatePromptRunRequestProvider;
  /** @nullable */
  triggered_by?: string | null;
}
