/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type GateFindingSeverity = typeof GateFindingSeverity[keyof typeof GateFindingSeverity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GateFindingSeverity = {
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const;
