/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { GateFindingSeverity } from './gateFindingSeverity';

export interface GateFinding {
  message: string;
  page_url: string;
  rule_id: string;
  severity: GateFindingSeverity;
}
