/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { GateFinding } from './gateFinding';

export interface GateSummary {
  passed: boolean;
  fail_on: string[];
  failed_findings: GateFinding[];
}
