/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

/**
 * Story 19.6 — 202 response from POST /v1/recommendations/generate. Per the Phase 2 async-write pattern, `status_url` points at the list endpoint where the results are readable.
 */
export interface GenerateRecommendationsAccepted {
  /** @minimum 0 */
  generated_count: number;
  /** @minimum 0 */
  inserted_count: number;
  status: string;
  status_url: string;
}
