/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export interface GrafanaCrawlerSeries {
  /**
     * @items.minItems 2
     * @items.maxItems 2
     */
  datapoints: number[][];
  target: string;
}
