/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export interface GrafanaCrawlerQuery {
  /**
   * @minimum 1
   * @maximum 365
   */
  days?: number;
  include_unverified?: boolean;
  target?: string;
}
