/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { ContributionStatus } from './contributionStatus';

/**
 * Result of recording an external run, including the benchmark contribution outcome.
 */
export interface IngestRunResponse {
  contribution: ContributionStatus;
  observed_at: string;
  project_id: string;
  prompt_slug: string;
  provider: string;
  run_id: string;
}
