/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

/**
 * Canonical external provider payload. May be plain text or structured JSON.
 */
export type IngestRunRequestRawResponse = string | { [key: string]: unknown } | unknown[] | number | boolean | null;
