/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

/**
 * Caller-supplied metadata persisted under request_parameters.metadata.
 * @nullable
 */
export type IngestRunRequestMetadata = { [key: string]: unknown } | null;
