/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { IngestSiteEventBodyProperties } from './ingestSiteEventBodyProperties';

export type IngestSiteEventBody = {
  /** Must be one of the 10-event taxonomy: page_view, leaderboard_view, brand_profile_view, contribute_start, contribute_step, contribute_complete, verify_start, verify_complete, verify_fail, badge_embed_view. Unknown values are silently dropped (204). */
  event_type: string;
  /** Site-relative path. */
  path?: string;
  /** Event-specific properties per the taxonomy. */
  properties?: IngestSiteEventBodyProperties;
  /** Referrer domain only (never a full URL). */
  referrer?: string;
  /** Ephemeral per-visit UUID generated client-side; not linked to identity. */
  session_id: string;
};
