/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

/**
 * Event-specific properties per the taxonomy.
 */
export type IngestSiteEventBodyProperties = { [key: string]: unknown };
