/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export interface KindAdoption {
  /** @minimum 0 */
  acted: number;
  /** @nullable */
  adoption_rate?: number | null;
  /** @minimum 0 */
  dismissed: number;
  kind: string;
  /** @minimum 0 */
  surfaced: number;
}
