/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type ListRecommendationsParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * Opaque page cursor from a previous response's next_cursor.
 */
cursor?: string;
};
