/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type ListAuditRunsParams = {
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};
