/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type OperatorConsentRecordsEvent = typeof OperatorConsentRecordsEvent[keyof typeof OperatorConsentRecordsEvent];


export const OperatorConsentRecordsEvent = {
  optin: 'optin',
  optout: 'optout',
} as const;
