/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type OperatorListEntitiesClaimStatus = typeof OperatorListEntitiesClaimStatus[keyof typeof OperatorListEntitiesClaimStatus];


export const OperatorListEntitiesClaimStatus = {
  unclaimed: 'unclaimed',
  pending: 'pending',
  verified: 'verified',
  revoked: 'revoked',
  pending_conflict: 'pending_conflict',
} as const;
