/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type OperatorConsentEventsEvent = typeof OperatorConsentEventsEvent[keyof typeof OperatorConsentEventsEvent];


export const OperatorConsentEventsEvent = {
  optin: 'optin',
  optout: 'optout',
} as const;
