/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type OperatorEntityRole = typeof OperatorEntityRole[keyof typeof OperatorEntityRole];


export const OperatorEntityRole = {
  brand: 'brand',
  source: 'source',
  both: 'both',
} as const;
