/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { OperatorConsentEventEvent } from './operatorConsentEventEvent';
import type { OperatorConsentEventTier } from './operatorConsentEventTier';

/**
 * Story 49.0 — an opt-in/opt-out event projected from benchmark_consent (event + terms_version + timestamp).
 */
export interface OperatorConsentEvent {
  created_at: string;
  event: OperatorConsentEventEvent;
  id: string;
  project_id: string;
  terms_version: string;
  tier: OperatorConsentEventTier;
}
