/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { OperatorListEntitiesClaimStatus } from './operatorListEntitiesClaimStatus';
import type { OperatorListEntitiesVerificationMethod } from './operatorListEntitiesVerificationMethod';

export type OperatorListEntitiesParams = {
claim_status?: OperatorListEntitiesClaimStatus;
verification_method?: OperatorListEntitiesVerificationMethod;
/**
 * Case-insensitive substring of the domain.
 */
domain?: string;
/**
 * @maximum 200
 */
limit?: number;
offset?: number;
};
