/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { OperatorConsentEventsEvent } from './operatorConsentEventsEvent';
import type { OperatorConsentEventsTier } from './operatorConsentEventsTier';

export type OperatorConsentEventsParams = {
tier?: OperatorConsentEventsTier;
project?: string;
event?: OperatorConsentEventsEvent;
from?: string;
to?: string;
/**
 * @maximum 200
 */
limit?: number;
offset?: number;
};
