/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type OperatorEntityClaimStatus = typeof OperatorEntityClaimStatus[keyof typeof OperatorEntityClaimStatus];


export const OperatorEntityClaimStatus = {
  unclaimed: 'unclaimed',
  pending: 'pending',
  verified: 'verified',
  revoked: 'revoked',
  pending_conflict: 'pending_conflict',
} as const;
