/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { OperatorVerificationAttempt } from './operatorVerificationAttempt';

/**
 * Story 48.4 — entity detail: the OperatorEntity fields plus its verification_attempts (newest-first).
 */
export interface OperatorEntityDetail {
  domain: string;
  display_name?: string;
  role?: string;
  claim_status?: string;
  /** @nullable */
  verified_at?: string | null;
  /** @nullable */
  verification_method?: string | null;
  /** @nullable */
  grace_period_start?: string | null;
  created_at?: string;
  updated_at?: string;
  verification_attempts: OperatorVerificationAttempt[];
}
