/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type OperatorConsentRecordTier = typeof OperatorConsentRecordTier[keyof typeof OperatorConsentRecordTier];


export const OperatorConsentRecordTier = {
  anonymous: 'anonymous',
  brand_visibility: 'brand_visibility',
} as const;
