/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { OperatorConsentRecordEvent } from './operatorConsentRecordEvent';
import type { OperatorConsentRecordTier } from './operatorConsentRecordTier';

/**
 * Story 49.0 — one row of the OSS-owned benchmark_consent ledger as seen by the Plane-1 operator read.
 */
export interface OperatorConsentRecord {
  /** @nullable */
  actor?: string | null;
  created_at: string;
  event: OperatorConsentRecordEvent;
  id: string;
  /** @nullable */
  note?: string | null;
  project_id: string;
  terms_version: string;
  tier: OperatorConsentRecordTier;
}
