/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { OperatorEntityClaimStatus } from './operatorEntityClaimStatus';
import type { OperatorEntityRole } from './operatorEntityRole';
import type { OperatorEntityVerificationMethod } from './operatorEntityVerificationMethod';

/**
 * Story 48.4 — an entity (claimed brand) as seen by the operator entity-admin surface.
 */
export interface OperatorEntity {
  domain: string;
  display_name: string;
  role: OperatorEntityRole;
  claim_status: OperatorEntityClaimStatus;
  /** @nullable */
  verified_at?: string | null;
  /** @nullable */
  verification_method?: OperatorEntityVerificationMethod;
  /** @nullable */
  grace_period_start?: string | null;
  created_at: string;
  updated_at: string;
}
