/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

/**
 * Story 48.4 — one row of an entity's append-only verification attempt history.
 */
export interface OperatorVerificationAttempt {
  id: string;
  method: string;
  state: string;
  expires_at: string;
  /** @nullable */
  consumed_at?: string | null;
  created_at: string;
}
