/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type OperatorListEntitiesVerificationMethod = typeof OperatorListEntitiesVerificationMethod[keyof typeof OperatorListEntitiesVerificationMethod];


export const OperatorListEntitiesVerificationMethod = {
  dns_txt: 'dns_txt',
  email_magic_link: 'email_magic_link',
  manual_override: 'manual_override',
} as const;
