/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type OperatorConsentEventsTier = typeof OperatorConsentEventsTier[keyof typeof OperatorConsentEventsTier];


export const OperatorConsentEventsTier = {
  anonymous: 'anonymous',
  brand_visibility: 'brand_visibility',
} as const;
