/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { OperatorConsentRecordsEvent } from './operatorConsentRecordsEvent';
import type { OperatorConsentRecordsTier } from './operatorConsentRecordsTier';

export type OperatorConsentRecordsParams = {
tier?: OperatorConsentRecordsTier;
project?: string;
event?: OperatorConsentRecordsEvent;
from?: string;
to?: string;
/**
 * @maximum 200
 */
limit?: number;
offset?: number;
};
