/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type OperatorConsentRecordsTier = typeof OperatorConsentRecordsTier[keyof typeof OperatorConsentRecordsTier];


export const OperatorConsentRecordsTier = {
  anonymous: 'anonymous',
  brand_visibility: 'brand_visibility',
} as const;
