/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type OperatorConsentEventTier = typeof OperatorConsentEventTier[keyof typeof OperatorConsentEventTier];


export const OperatorConsentEventTier = {
  anonymous: 'anonymous',
  brand_visibility: 'brand_visibility',
} as const;
