/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { AuditFinding } from './auditFinding';

export interface PageAudit {
  findings: AuditFinding[];
  /**
   * @minimum 0
   * @maximum 100
   */
  score: number;
  /** @nullable */
  title?: string | null;
  url: string;
}
