/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { AuditFinding } from './auditFinding';

export interface PageAudit {
  url: string;
  /** @nullable */
  title?: string | null;
  /**
     * @minimum 0
     * @maximum 100
     */
  score: number;
  findings: AuditFinding[];
}
