/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type PluginStatusStatus = typeof PluginStatusStatus[keyof typeof PluginStatusStatus];


export const PluginStatusStatus = {
  loaded: 'loaded',
  skipped: 'skipped',
  load_error: 'load_error',
} as const;
