/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { PluginStatusKind } from './pluginStatusKind';
import type { PluginStatusStatus } from './pluginStatusStatus';

/**
 * Story 41.2 — runtime activation status of one installed plugin, as resolved at `anseo serve` boot. `anseo plugin list` renders the same fields.
 */
export interface PluginStatus {
  /** Plugin id (`namespace/name`). */
  id: string;
  kind: PluginStatusKind;
  /** Human-readable reason for a `skipped` / `load_error` outcome; absent when `loaded`. */
  reason?: string;
  status: PluginStatusStatus;
  version: string;
}
