/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type PluginStatusKind = typeof PluginStatusKind[keyof typeof PluginStatusKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PluginStatusKind = {
  provider: 'provider',
  extractor: 'extractor',
  analytics: 'analytics',
  'output-format': 'output-format',
  unknown: 'unknown',
} as const;
