/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { ProjectView } from './projectView';

export interface ProjectListResponse {
  projects: ProjectView[];
}
