/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type RecommendationReproducibility = {
  class: string;
  /** @nullable */
  note?: string | null;
};
