/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { Recommendation } from './recommendation';

/**
 * Story 19.6 — cursor-paginated active recommendations. `next_cursor` is null on the last page.
 */
export interface RecommendationListResponse {
  items: Recommendation[];
  /**
   * Opaque cursor for the next page; null when no further pages remain.
   * @nullable
   */
  next_cursor: string | null;
}
