/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type RecommendationState = typeof RecommendationState[keyof typeof RecommendationState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecommendationState = {
  generated: 'generated',
  surfaced: 'surfaced',
  acknowledged: 'acknowledged',
  acted: 'acted',
  measured: 'measured',
  dismissed: 'dismissed',
  stale: 'stale',
} as const;
