/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { RecommendationPayload } from './recommendationPayload';
import type { RecommendationReproducibility } from './recommendationReproducibility';
import type { RecommendationState } from './recommendationState';
import type { RecommendationTraceability } from './recommendationTraceability';

/**
 * Story 19.6 — a stored GEO Recommendation (architecture-phase3-geo-recommendations.md §8 wire shape) plus its DB lifecycle `state`.
 */
export interface Recommendation {
  confidence_band: string;
  engine_version: string;
  generated_at: string;
  /** ULID. */
  id: string;
  kind: string;
  payload: RecommendationPayload;
  /** ULID. */
  project_id: string;
  reproducibility: RecommendationReproducibility;
  severity: string;
  state: RecommendationState;
  summary: string;
  tags: string[];
  traceability: RecommendationTraceability;
}
