/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { RunListResponseRunsItem } from './runListResponseRunsItem';

export interface RunListResponse {
  runs?: RunListResponseRunsItem[];
}
