/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { SetupStatusClickhouseState } from './setupStatusClickhouseState';

export type SetupStatusClickhouse = {
  error?: string;
  /** @nullable */
  etl_lag_seconds?: number | null;
  /** @nullable */
  row_count?: number | null;
  state: SetupStatusClickhouseState;
  /** @nullable */
  url?: string | null;
};
