/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type SetupStatusWebhookTarget = {
  configured: boolean;
  error?: string;
  /** @nullable */
  last_delivery_at?: string | null;
  /** @nullable */
  last_status?: string | null;
};
