/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { SetupStatusWorkerState } from './setupStatusWorkerState';

export type SetupStatusWorker = {
  error?: string;
  /** @nullable */
  queue_depth?: number | null;
  state: SetupStatusWorkerState;
  /** @nullable */
  uptime_seconds?: number | null;
};
