/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { SetupStatusPostgresState } from './setupStatusPostgresState';

export type SetupStatusPostgres = {
  error?: string;
  /** @nullable */
  last_write_at?: string | null;
  /** @nullable */
  row_count_estimate?: number | null;
  /** @nullable */
  schema_version?: number | null;
  state: SetupStatusPostgresState;
};
