/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { SetupStatusApiKeysItem } from './setupStatusApiKeysItem';
import type { SetupStatusClickhouse } from './setupStatusClickhouse';
import type { SetupStatusDocker } from './setupStatusDocker';
import type { SetupStatusPostgres } from './setupStatusPostgres';
import type { SetupStatusWebhookTarget } from './setupStatusWebhookTarget';
import type { SetupStatusWorker } from './setupStatusWorker';

/**
 * Story 15.1 — best-effort status probe across all deployment surfaces. Always returned 200; individual sections carry `state: "unknown"` + an `error` string on failure (per-probe timeout: 1s; 500ms for Docker).
 */
export interface SetupStatus {
  api_keys: SetupStatusApiKeysItem[];
  clickhouse: SetupStatusClickhouse;
  docker: SetupStatusDocker;
  postgres: SetupStatusPostgres;
  webhook_target: SetupStatusWebhookTarget;
  worker: SetupStatusWorker;
}
