/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type SetupStatusWorkerState = typeof SetupStatusWorkerState[keyof typeof SetupStatusWorkerState];


export const SetupStatusWorkerState = {
  running: 'running',
  stopped: 'stopped',
  unknown: 'unknown',
} as const;
