/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type SetupStatusApiKeysItem = {
  configured: boolean;
  /** @nullable */
  last_used_at?: string | null;
  provider: string;
};
