/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type SetupStatusClickhouseState = typeof SetupStatusClickhouseState[keyof typeof SetupStatusClickhouseState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SetupStatusClickhouseState = {
  healthy: 'healthy',
  degraded: 'degraded',
  not_configured: 'not_configured',
  unknown: 'unknown',
} as const;
