/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type SetupStatusPostgresState = typeof SetupStatusPostgresState[keyof typeof SetupStatusPostgresState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SetupStatusPostgresState = {
  healthy: 'healthy',
  degraded: 'degraded',
  unknown: 'unknown',
} as const;
