/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

/**
 * Story 19.5 — SM-14 adoption metric. `rate` is null when the denominator is zero.
 */
export interface Sm14MetricResponse {
  denominator: number;
  numerator: number;
  /** @nullable */
  rate?: number | null;
}
