/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

/**
 * Story 40.5 — one canonical GEO benchmark prompt slug exposed for instrumentation parity helpers.
 */
export interface SuitePromptSummary {
  slug: string;
  version: string;
  description: string;
}
