/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { Recommendation } from './recommendation';
import type { TransitionRecommendationResponseWarningsItem } from './transitionRecommendationResponseWarningsItem';

export interface TransitionRecommendationResponse {
  recommendation: Recommendation;
  warnings: TransitionRecommendationResponseWarningsItem[];
}
