/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { TransitionRecommendationRequestTo } from './transitionRecommendationRequestTo';

/**
 * Story 19.6 — lifecycle transition (Story 19.4 state machine). Illegal edges return 409.
 */
export interface TransitionRecommendationRequest {
  /** @nullable */
  evidence_url?: string | null;
  /** @nullable */
  note?: string | null;
  to: TransitionRecommendationRequestTo;
}
