/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export type TransitionRecommendationRequestTo = typeof TransitionRecommendationRequestTo[keyof typeof TransitionRecommendationRequestTo];


export const TransitionRecommendationRequestTo = {
  surfaced: 'surfaced',
  acknowledged: 'acknowledged',
  acted: 'acted',
  measured: 'measured',
  dismissed: 'dismissed',
  stale: 'stale',
} as const;
