/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */

export interface VisibilitySentimentPoint {
  prompt: string;
  provider: string;
  entity: string;
  day: string;
  positive: number;
  neutral: number;
  negative: number;
  total: number;
  positive_share: number;
  neutral_share: number;
  negative_share: number;
  average_score: number;
}
