/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type { VisibilitySentimentPoint } from './visibilitySentimentPoint';

export interface VisibilitySentimentResponse {
  points: VisibilitySentimentPoint[];
  window_days: number;
}
