#!/usr/bin/env bash
# =============================================================================
# make-compose-snapshot.sh — Story 38.19 / 38.16
#
# Produce a version-PINNED snapshot of the standalone production compose bundle
# for a release. The release-train calls this on a vX.Y.Z tag to materialize the
# artifact that gets served from the stable versioned URL:
#
#     https://anseo.ai/compose/<X.Y.Z>.yml
#
# The standalone compose.yml parameterizes the app image tag via ${ANSEO_VERSION}
# (X.Y.Z, no leading v — matching docker/metadata-action {{version}}). Operators
# pulling the *unpinned* compose.yml supply ANSEO_VERSION via .env; a *snapshot*
# instead bakes the version in so a one-line `curl` yields a fully pinned bundle
# requiring no ANSEO_VERSION in .env.
#
# Usage:
#   scripts/make-compose-snapshot.sh <X.Y.Z> [out-dir]
#
#   <X.Y.Z>   bare semver (no leading v). Must match the published image tags.
#   [out-dir] where to write <X.Y.Z>.yml (+ a copy named compose.yml). Default:
#             dist/compose
#
# Output:
#   <out-dir>/<X.Y.Z>.yml   — pinned snapshot (upload to /compose/<X.Y.Z>.yml)
#
# It does NOT publish anything; it only renders the artifact. The publish step
# (upload to the docs-site bucket / repository_dispatch to the site repo) is
# wired in the release-train workflow and gated on the relevant token.
# =============================================================================
set -euo pipefail

VERSION="${1:?usage: make-compose-snapshot.sh <X.Y.Z> [out-dir]}"
OUT_DIR="${2:-dist/compose}"

# Reject a leading v / arbitrary refs — the snapshot name and the baked image
# tag must be the exact X.Y.Z the images were published under.
if ! printf '%s' "${VERSION}" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+([._+-][0-9A-Za-z.]+)?$'; then
  echo "ERROR: version must be a bare X.Y.Z (no leading v): got '${VERSION}'" >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SRC="${REPO_ROOT}/infra/standalone/compose.yml"

if [ ! -r "${SRC}" ]; then
  echo "ERROR: standalone compose source not found: ${SRC}" >&2
  exit 1
fi

mkdir -p "${OUT_DIR}"
DEST="${OUT_DIR}/${VERSION}.yml"

# Bake ANSEO_VERSION's default to the pinned version. The source uses the form
#   ${ANSEO_VERSION:?set ANSEO_VERSION to a pinned X.Y.Z in .env}
# Replace that REQUIRED-var form with a DEFAULTED form pinned to this release:
#   ${ANSEO_VERSION:-X.Y.Z}
# so the snapshot needs no ANSEO_VERSION in .env, while still letting an operator
# override it. Done with a literal-safe sed (version is validated above).
{
  printf '# Pinned standalone snapshot for Anseo %s — generated by scripts/make-compose-snapshot.sh.\n' "${VERSION}"
  printf '# Source: infra/standalone/compose.yml. Served from https://anseo.ai/compose/%s.yml\n' "${VERSION}"
  printf '# ANSEO_VERSION is baked to %s; override in .env only to deviate from this release.\n' "${VERSION}"
  sed -E "s/\\\$\{ANSEO_VERSION:[?][^}]*\}/\${ANSEO_VERSION:-${VERSION}}/g" "${SRC}"
} > "${DEST}"

# Sanity: every app image in the snapshot must now resolve to this version even
# with no ANSEO_VERSION set. Grep the baked default form.
for app in api worker web; do
  if ! grep -Eq "/${app}:\\\$\{ANSEO_VERSION:-${VERSION}\}" "${DEST}"; then
    echo "ERROR: ${app} image in snapshot is not pinned to ${VERSION}" >&2
    echo "  (expected baked default \${ANSEO_VERSION:-${VERSION}})" >&2
    exit 1
  fi
done

echo "wrote pinned compose snapshot: ${DEST}"
