/*
 * AUTO-GENERATED by orval from crates/wire-schema/openapi.json.
 * DO NOT EDIT BY HAND. Regenerate with `make -C infra/codegen ts`.
 */
import type {
  AuditReport,
  AuditRequest,
  AuditRunList,
  BrandUpdate,
  BrandUpdateResult,
  BrandView,
  CitationSummaryParams,
  CitationSummaryResponse,
  ClickHouseInstallAccepted,
  ClickHouseInstallEvent,
  ClickhouseInstallStreamParams,
  ComparisonsParams,
  ComparisonsResponse,
  CrawlReferReport,
  CrawlerIngestRequest,
  CrawlerIngestResult,
  CrawlerMetricsParams,
  CrawlerMetricsResponse,
  CrawlerRatioParams,
  CreateProjectRequest,
  CreateProjectResponse,
  CreatePromptRunRequest,
  CreatePromptRunResponse,
  GenerateRecommendationsAccepted,
  GrafanaCrawlerQuery,
  GrafanaCrawlerSeries,
  ListAuditRunsParams,
  ListRecommendationsParams,
  ListRunsParams,
  ProjectListResponse,
  ProjectView,
  Recommendation,
  RecommendationIntelligence,
  RecommendationListResponse,
  RunListResponse,
  SetupStatus,
  Sm14MetricResponse,
  TransitionRecommendationRequest,
  TransitionRecommendationResponse,
  VisibilitySentimentParams,
  VisibilitySentimentResponse,
  VisibilityTrendParams,
  VisibilityTrendResponse
} from './schemas'
import { fetchClient } from './runtime';

/**
 * @summary Roadmap Epic 32 — crawl a URL/sitemap and score citation-readiness against in-tree heuristics (Identity, Extractability, Corroboration). Optional CI-gate thresholds.
 */
export type runAuditResponse = {
  data: AuditReport;
  status: number;
}

export const getRunAuditUrl = () => {


  return `/v1/audit`
}

export const runAudit = async (auditRequest: AuditRequest, options?: RequestInit): Promise<runAuditResponse> => {
  
  return fetchClient<Promise<runAuditResponse>>(getRunAuditUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(
      auditRequest,)
  }
);}



/**
 * @summary Roadmap Epic 32 — persisted site-audit history for the project, newest first.
 */
export type listAuditRunsResponse = {
  data: AuditRunList;
  status: number;
}

export const getListAuditRunsUrl = (params?: ListAuditRunsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  return normalizedParams.size ? `/v1/audit/runs?${normalizedParams.toString()}` : `/v1/audit/runs`
}

export const listAuditRuns = async (params?: ListAuditRunsParams, options?: RequestInit): Promise<listAuditRunsResponse> => {
  
  return fetchClient<Promise<listAuditRunsResponse>>(getListAuditRunsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type citationSummaryResponse = {
  data: CitationSummaryResponse;
  status: number;
}

export const getCitationSummaryUrl = (params?: CitationSummaryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  return normalizedParams.size ? `/v1/citations/summary?${normalizedParams.toString()}` : `/v1/citations/summary`
}

export const citationSummary = async (params?: CitationSummaryParams, options?: RequestInit): Promise<citationSummaryResponse> => {
  
  return fetchClient<Promise<citationSummaryResponse>>(getCitationSummaryUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Phase 3 Story 0.8 — deterministic brand-vs-competitors comparison matrix (substrate for MCP `compare_brands`).
 */
export type comparisonsResponse = {
  data: ComparisonsResponse;
  status: number;
}

export const getComparisonsUrl = (params: ComparisonsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  return normalizedParams.size ? `/v1/comparisons?${normalizedParams.toString()}` : `/v1/comparisons`
}

export const comparisons = async (params: ComparisonsParams, options?: RequestInit): Promise<comparisonsResponse> => {
  
  return fetchClient<Promise<comparisonsResponse>>(getComparisonsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Roadmap Epic 31 — ingest raw web-server access-log lines, normalize + verify bot identity, and write crawler events for this project.
 */
export type crawlerIngestResponse = {
  data: CrawlerIngestResult;
  status: number;
}

export const getCrawlerIngestUrl = () => {


  return `/v1/crawlers/ingest`
}

export const crawlerIngest = async (crawlerIngestRequest: CrawlerIngestRequest, options?: RequestInit): Promise<crawlerIngestResponse> => {
  
  return fetchClient<Promise<crawlerIngestResponse>>(getCrawlerIngestUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(
      crawlerIngestRequest,)
  }
);}



/**
 * @summary Roadmap Epic 31 — crawler frequency, top paths, stuck/error pages, and trend. Verified-only by default.
 */
export type crawlerMetricsResponse = {
  data: CrawlerMetricsResponse;
  status: number;
}

export const getCrawlerMetricsUrl = (params?: CrawlerMetricsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  return normalizedParams.size ? `/v1/crawlers/metrics?${normalizedParams.toString()}` : `/v1/crawlers/metrics`
}

export const crawlerMetrics = async (params?: CrawlerMetricsParams, options?: RequestInit): Promise<crawlerMetricsResponse> => {
  
  return fetchClient<Promise<crawlerMetricsResponse>>(getCrawlerMetricsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Roadmap Epic 33 — crawl-to-refer ratio by verified bot, degraded to crawls_only until referral attribution exists.
 */
export type crawlerRatioResponse = {
  data: CrawlReferReport;
  status: number;
}

export const getCrawlerRatioUrl = (params?: CrawlerRatioParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  return normalizedParams.size ? `/v1/crawlers/ratio?${normalizedParams.toString()}` : `/v1/crawlers/ratio`
}

export const crawlerRatio = async (params?: CrawlerRatioParams, options?: RequestInit): Promise<crawlerRatioResponse> => {
  
  return fetchClient<Promise<crawlerRatioResponse>>(getCrawlerRatioUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Roadmap Epic 31 — Grafana JSON datasource query for crawler trends.
 */
export type grafanaCrawlerQueryResponse = {
  data: GrafanaCrawlerSeries[];
  status: number;
}

export const getGrafanaCrawlerQueryUrl = () => {


  return `/v1/grafana/crawlers/query`
}

export const grafanaCrawlerQuery = async (grafanaCrawlerQuery: GrafanaCrawlerQuery, options?: RequestInit): Promise<grafanaCrawlerQueryResponse> => {
  
  return fetchClient<Promise<grafanaCrawlerQueryResponse>>(getGrafanaCrawlerQueryUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(
      grafanaCrawlerQuery,)
  }
);}



/**
 * @summary Health probe
 */
export type healthzResponse = {
  data: string;
  status: number;
}

export const getHealthzUrl = () => {


  return `/v1/healthz`
}

export const healthz = async ( options?: RequestInit): Promise<healthzResponse> => {
  
  return fetchClient<Promise<healthzResponse>>(getHealthzUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary List active (non-archived) projects. Operator-scoped; not gated by X-OpenGEO-Project.
 */
export type listProjectsResponse = {
  data: ProjectListResponse;
  status: number;
}

export const getListProjectsUrl = () => {


  return `/v1/projects`
}

export const listProjects = async ( options?: RequestInit): Promise<listProjectsResponse> => {
  
  return fetchClient<Promise<listProjectsResponse>>(getListProjectsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create a project from a brand. project_id is derived from the name and returned.
 */
export type createProjectResponse = {
  data: CreateProjectResponse;
  status: number;
}

export const getCreateProjectUrl = () => {


  return `/v1/projects`
}

export const createProject = async (createProjectRequest: CreateProjectRequest, options?: RequestInit): Promise<createProjectResponse> => {
  
  return fetchClient<Promise<createProjectResponse>>(getCreateProjectUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(
      createProjectRequest,)
  }
);}



/**
 * @summary Fetch a single project by id.
 */
export type getProjectResponse = {
  data: ProjectView;
  status: number;
}

export const getGetProjectUrl = (id: string,) => {


  return `/v1/projects/${id}`
}

export const getProject = async (id: string, options?: RequestInit): Promise<getProjectResponse> => {
  
  return fetchClient<Promise<getProjectResponse>>(getGetProjectUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Soft-delete a project (idempotent). It drops out of the list but its data is preserved.
 */
export type archiveProjectResponse = {
  data: void;
  status: number;
}

export const getArchiveProjectUrl = (id: string,) => {


  return `/v1/projects/${id}/archive`
}

export const archiveProject = async (id: string, options?: RequestInit): Promise<archiveProjectResponse> => {
  
  return fetchClient<Promise<archiveProjectResponse>>(getArchiveProjectUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Server-Sent Events stream of ARCH-17 lifecycle events for one project.
 */
export type subscribeEventsResponse = {
  data: unknown;
  status: number;
}

export const getSubscribeEventsUrl = (projectId: string,) => {


  return `/v1/projects/${projectId}/events`
}

export const subscribeEvents = async (projectId: string, options?: RequestInit): Promise<subscribeEventsResponse> => {
  
  return fetchClient<Promise<subscribeEventsResponse>>(getSubscribeEventsUrl(projectId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Dispatch a one-shot prompt run for an already-declared Prompt and Provider.
 */
export type createPromptRunResponse = {
  data: CreatePromptRunResponse;
  status: number;
}

export const getCreatePromptRunUrl = () => {


  return `/v1/prompt-runs`
}

export const createPromptRun = async (createPromptRunRequest: CreatePromptRunRequest, options?: RequestInit): Promise<createPromptRunResponse> => {
  
  return fetchClient<Promise<createPromptRunResponse>>(getCreatePromptRunUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(
      createPromptRunRequest,)
  }
);}



/**
 * @summary Story 19.6 — cursor-paginated active recommendations for the project, newest first.
 */
export type listRecommendationsResponse = {
  data: RecommendationListResponse;
  status: number;
}

export const getListRecommendationsUrl = (params?: ListRecommendationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  return normalizedParams.size ? `/v1/recommendations?${normalizedParams.toString()}` : `/v1/recommendations`
}

export const listRecommendations = async (params?: ListRecommendationsParams, options?: RequestInit): Promise<listRecommendationsResponse> => {
  
  return fetchClient<Promise<listRecommendationsResponse>>(getListRecommendationsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Story 19.6 — assemble an EngineInput from the project's live prompts/runs/citations, run the in-process engine, and persist the result. Returns 202 + a status_url per the Phase 2 async-write pattern.
 */
export type generateRecommendationsResponse = {
  data: GenerateRecommendationsAccepted;
  status: number;
}

export const getGenerateRecommendationsUrl = () => {


  return `/v1/recommendations/generate`
}

export const generateRecommendations = async ( options?: RequestInit): Promise<generateRecommendationsResponse> => {
  
  return fetchClient<Promise<generateRecommendationsResponse>>(getGenerateRecommendationsUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Story 19.5+ — per-kind adoption: surfaced / acted / dismissed counts (the what-works-vs-what-doesn't loop). First-party only.
 */
export type recommendationIntelligenceResponse = {
  data: RecommendationIntelligence;
  status: number;
}

export const getRecommendationIntelligenceUrl = () => {


  return `/v1/recommendations/intelligence`
}

export const recommendationIntelligence = async ( options?: RequestInit): Promise<recommendationIntelligenceResponse> => {
  
  return fetchClient<Promise<recommendationIntelligenceResponse>>(getRecommendationIntelligenceUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Story 19.5 — SM-14 adoption metric for the project (Acted∨Measured / Surfaced∨later, first-party Kinds only).
 */
export type recommendationMetricsResponse = {
  data: Sm14MetricResponse;
  status: number;
}

export const getRecommendationMetricsUrl = () => {


  return `/v1/recommendations/metrics`
}

export const recommendationMetrics = async ( options?: RequestInit): Promise<recommendationMetricsResponse> => {
  
  return fetchClient<Promise<recommendationMetricsResponse>>(getRecommendationMetricsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Story 19.6 — one recommendation + full traceability. 404 when the row is absent or owned by another project.
 */
export type getRecommendationResponse = {
  data: Recommendation;
  status: number;
}

export const getGetRecommendationUrl = (id: string,) => {


  return `/v1/recommendations/${id}`
}

export const getRecommendation = async (id: string, options?: RequestInit): Promise<getRecommendationResponse> => {
  
  return fetchClient<Promise<getRecommendationResponse>>(getGetRecommendationUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Story 19.6 — apply a lifecycle transition (Story 19.4 state machine). Illegal transitions return 409.
 */
export type transitionRecommendationResponse = {
  data: TransitionRecommendationResponse;
  status: number;
}

export const getTransitionRecommendationUrl = (id: string,) => {


  return `/v1/recommendations/${id}/state`
}

export const transitionRecommendation = async (id: string,
    transitionRecommendationRequest: TransitionRecommendationRequest, options?: RequestInit): Promise<transitionRecommendationResponse> => {
  
  return fetchClient<Promise<transitionRecommendationResponse>>(getTransitionRecommendationUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(
      transitionRecommendationRequest,)
  }
);}



/**
 * @summary List recent Prompt Runs
 */
export type listRunsResponse = {
  data: RunListResponse;
  status: number;
}

export const getListRunsUrl = (params?: ListRunsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  return normalizedParams.size ? `/v1/runs?${normalizedParams.toString()}` : `/v1/runs`
}

export const listRuns = async (params?: ListRunsParams, options?: RequestInit): Promise<listRunsResponse> => {
  
  return fetchClient<Promise<listRunsResponse>>(getListRunsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Read the DB-authoritative brand config (name, variants, competitors, site_url).
 */
export type getBrandResponse = {
  data: BrandView;
  status: number;
}

export const getGetBrandUrl = () => {


  return `/v1/setup/brand`
}

export const getBrand = async ( options?: RequestInit): Promise<getBrandResponse> => {
  
  return fetchClient<Promise<getBrandResponse>>(getGetBrandUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Update brand config. Changing the name re-derives project_id (allowed only before the first run) and sets restart_required.
 */
export type updateBrandResponse = {
  data: BrandUpdateResult;
  status: number;
}

export const getUpdateBrandUrl = () => {


  return `/v1/setup/brand`
}

export const updateBrand = async (brandUpdate: BrandUpdate, options?: RequestInit): Promise<updateBrandResponse> => {
  
  return fetchClient<Promise<updateBrandResponse>>(getUpdateBrandUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(
      brandUpdate,)
  }
);}



/**
 * @summary Story 15.1 — kick off (MOCK) ClickHouse local-install state machine. Returns 202 with a ULID and an SSE stream URL. Real Docker calls land in Story 15.3.
 */
export type clickhouseInstallResponse = {
  data: ClickHouseInstallAccepted;
  status: number;
}

export const getClickhouseInstallUrl = () => {


  return `/v1/setup/clickhouse/install`
}

export const clickhouseInstall = async ( options?: RequestInit): Promise<clickhouseInstallResponse> => {
  
  return fetchClient<Promise<clickhouseInstallResponse>>(getClickhouseInstallUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Story 15.1 — SSE stream of install progress events keyed by `id` (the ULID returned from POST /v1/setup/clickhouse/install). Closes when state reaches `complete` or `failed`.
 */
export type clickhouseInstallStreamResponse = {
  data: ClickHouseInstallEvent;
  status: number;
}

export const getClickhouseInstallStreamUrl = (params: ClickhouseInstallStreamParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  return normalizedParams.size ? `/v1/setup/clickhouse/install-stream?${normalizedParams.toString()}` : `/v1/setup/clickhouse/install-stream`
}

export const clickhouseInstallStream = async (params: ClickhouseInstallStreamParams, options?: RequestInit): Promise<clickhouseInstallStreamResponse> => {
  
  return fetchClient<Promise<clickhouseInstallStreamResponse>>(getClickhouseInstallStreamUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Story 15.1 — synchronous status probe across Postgres, ClickHouse, worker, webhook target, API keys, and Docker. Always returns 200; individual sections report `state: "unknown"` on probe failure or timeout.
 */
export type setupStatusResponse = {
  data: SetupStatus;
  status: number;
}

export const getSetupStatusUrl = () => {


  return `/v1/setup/status`
}

export const setupStatus = async ( options?: RequestInit): Promise<setupStatusResponse> => {
  
  return fetchClient<Promise<setupStatusResponse>>(getSetupStatusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Roadmap Epic 30 — sentiment aggregate under the existing visibility resource.
 */
export type visibilitySentimentResponse = {
  data: VisibilitySentimentResponse;
  status: number;
}

export const getVisibilitySentimentUrl = (params?: VisibilitySentimentParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  return normalizedParams.size ? `/v1/visibility/sentiment?${normalizedParams.toString()}` : `/v1/visibility/sentiment`
}

export const visibilitySentiment = async (params?: VisibilitySentimentParams, options?: RequestInit): Promise<visibilitySentimentResponse> => {
  
  return fetchClient<Promise<visibilitySentimentResponse>>(getVisibilitySentimentUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



export type visibilityTrendResponse = {
  data: VisibilityTrendResponse;
  status: number;
}

export const getVisibilityTrendUrl = (params: VisibilityTrendParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  return normalizedParams.size ? `/v1/visibility/trend?${normalizedParams.toString()}` : `/v1/visibility/trend`
}

export const visibilityTrend = async (params: VisibilityTrendParams, options?: RequestInit): Promise<visibilityTrendResponse> => {
  
  return fetchClient<Promise<visibilityTrendResponse>>(getVisibilityTrendUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



